# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad0916e7594824088af71bcb16b6d21a68fc3702d7b0c84725298897a0aa2d5c41122cac39335f6708cc47d4f5ada633b27fd7afa21a23f459491c1e5914c17f

test:
  secret_key_base: c4b94b33aea591af90a2e32a5998ca68d16efe4eef90213c28ba9ca2bc8717c96c97b5f96924c62e52339db9035a18411723ce26783873960a0fb6fd8bfd3b5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
